/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.easymarket.view;

import br.com.senai.easymarket.model.Fornecedor;
import br.com.senai.easymarket.model.Pedido;
import br.com.senai.easymarket.persistencia.controller.FornecedorController;
import br.com.senai.easymarket.persistencia.controller.PedidoController;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Marques
 */
public class JanelaInserirPedido extends javax.swing.JFrame {
    Fornecedor id;
    /**
     * Construtor da janela
     */
    public JanelaInserirPedido() {
        initComponents();
        FornecedorController d = new FornecedorController();
        d.listarFornecedor();
        for (Fornecedor c : d.listarFornecedor()) {
           comboFornecedor.addItem(c.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCliente = new javax.swing.JPanel();
        botaoCadastrarPedido = new javax.swing.JButton();
        campoCodigo = new javax.swing.JTextField();
        labelCodigo = new javax.swing.JLabel();
        labelDataPedido = new javax.swing.JLabel();
        labelValidade = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        LabelDescricao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboFornecedor = new javax.swing.JComboBox();
        campoDataPedido = new javax.swing.JTextField();
        campoDataEntrega = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelCliente.setBackground(new java.awt.Color(16, 156, 208));

        botaoCadastrarPedido.setText("Cadastrar");
        botaoCadastrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarPedidoActionPerformed(evt);
            }
        });

        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        labelCodigo.setText("Código:");

        labelDataPedido.setText("Data Pedido:");

        labelValidade.setText("Data Entrega:");

        labelValor.setText("Valor:");

        campoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorActionPerformed(evt);
            }
        });

        LabelDescricao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelDescricao.setText("Inserir Pedido");

        jLabel1.setText("Fornecedor:");

        comboFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFornecedorActionPerformed(evt);
            }
        });

        campoDataPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelClienteLayout = new javax.swing.GroupLayout(painelCliente);
        painelCliente.setLayout(painelClienteLayout);
        painelClienteLayout.setHorizontalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClienteLayout.createSequentialGroup()
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelClienteLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoCadastrarPedido)
                            .addGroup(painelClienteLayout.createSequentialGroup()
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelCodigo)
                                        .addComponent(labelDataPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelValidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel1))
                                .addGap(65, 65, 65)
                                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(campoValor)
                                    .addComponent(comboFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoDataPedido)
                                    .addComponent(campoDataEntrega)))))
                    .addGroup(painelClienteLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(LabelDescricao)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        painelClienteLayout.setVerticalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClienteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(LabelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataPedido)
                    .addComponent(campoDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValidade)
                    .addComponent(campoDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValor)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(botaoCadastrarPedido)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(painelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void botaoCadastrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarPedidoActionPerformed
     // Setando os valores que estavam no formulário para o objeto pedido criado
        Pedido c = new Pedido();
        c.setCodigo(campoCodigo.getText());
        String fornecedor = comboFornecedor.getSelectedItem().toString();
        pegarFornecedor(fornecedor);
        c.setFornecedor(id);
        c.setValor(Double.parseDouble(campoValor.getText()));
        // formatando a data para cadastrar bo banco de dados
        try{
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");  
            java.sql.Date data = new java.sql.Date(format.parse(campoDataPedido.getText()).getTime()); 
            c.setDataPedido(data);
            java.sql.Date data2 = new java.sql.Date(format.parse(campoDataEntrega.getText()).getTime()); 
            c.setDataEntrega(data2);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao converter data.");
        }
        PedidoController cc = new PedidoController();
        if(cc.salvar(c)){
            dispose();
            JanelaGerenciarPedidos jc = new JanelaGerenciarPedidos();
            jc.setVisible(true);
        }
    }//GEN-LAST:event_botaoCadastrarPedidoActionPerformed

    private void campoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorActionPerformed

    private void comboFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFornecedorActionPerformed

    private void campoDataPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataPedidoActionPerformed


    public void pegarFornecedor(String nome){
        // buscando fornecedor por nome paracadastrar seu id no banco de dados
        FornecedorController f = new FornecedorController();
        f.listarFornecedorByNome(nome);
        for (Fornecedor c : f.listarFornecedorByNome(nome)) {
           id = c;
        }
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDescricao;
    private javax.swing.JButton botaoCadastrarPedido;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoDataEntrega;
    private javax.swing.JTextField campoDataPedido;
    private javax.swing.JTextField campoValor;
    private javax.swing.JComboBox comboFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelDataPedido;
    private javax.swing.JLabel labelValidade;
    private javax.swing.JLabel labelValor;
    private javax.swing.JPanel painelCliente;
    // End of variables declaration//GEN-END:variables
}
